### ISSUE TITLE
Converted file too big compared to original video

### ISSUE THREAD

**Issue by uponatime2019** [Tyrrrz/YoutubeExplode.Converter#18]
Hello, I tried with some youtube videos, but the result video is too big in size
For example, the video 1080p without audio size is 46MB
After download and convert (using your example code), the video file size is ~ 170MB. How can I make it smaller (about 50MB = video size + audio size)

**Comment by Tyrrrz** [comment]
I think it's because FFmpeg is executed with the 'fast' preset that favors speed over compression. To add flexibility, there needs to be an option to configure presets.

**Comment by uponatime2019** [comment]
As your suggest I just test for some preset and here is the result. I think default option should not be ultrafast. And with small files like this video, the time ffmpeg take to convert is not much different
![image](https://user-images.githubusercontent.com/15900671/75025849-7a4bb700-54ce-11ea-8e67-aa87a2b2bc40.png)

**Comment by Tyrrrz** [comment]
I agree, this has to be changed. I initially chose ultrafast because it would take unbearably long when muxing streams in different containers (e.g. webm+mp4), but it's not an issue for streams with the same containers.

I don't think the function should expose the preset directly but rather have an enum that let's you choose compression level. Open for PR if anyone is interested.
